### PR TITLE
Debianization of wayvnc

### PR DESCRIPTION
**Pull request by jauntywunderkind**
Hello, this builds off of https://github.com/any1/neatvnc/pull/61 and https://github.com/any1/aml/pull/7 . 

Check out and run `debuild` and it should build the following files in the parent directory:

```
wayvnc_20211011-1_amd64.build
wayvnc_20211011-1_amd64.buildinfo
wayvnc_20211011-1_amd64.changes
wayvnc_20211011-1_amd64.deb
wayvnc_20211011-1.debian.tar.xz
wayvnc_20211011-1.dsc
wayvnc_20211011.orig.tar.xz
wayvnc-dbgsym_20211011-1_amd64.deb
```

This might either supplant or re-inform what we want to do in #92.

### CODE REVIEW

**Comment by any1** [comment]
Thanks, but I'd rather not have packaging scripts/recipes in here. That would make me responsible for them, and I'm not interested in maintaining them. All other distros use out-of-tree packaging anyway.

**Comment by fmoessbauer** [comment]
@jauntywunderkind There is already an ITP request for this package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002590

I just checked your debianization and it already looks pretty good. If you want to speed up things a bit, move the debianzation to Debian salsa and add a note on the ITP.

**Comment by josch** [comment]
I already [packaged vnc](https://salsa.debian.org/debian/wayvnc) and [uploaded it to NEW](https://ftp-master.debian.org/new/wayvnc_0.4.1-1.html).

But if you want to help maintain the package I'd be happy to sponsor your work. Create yourself an account on salsa and once the next wayvnc version is released, package it up and contact me at josch@debian.org and I'll review your packaging and upload it into unstable.

Boyuan Yang might also appreciate help with aml and neatvnc. You can contact Boyuan Yang via email at byang@debian.org.

Thanks!

**Comment by lack** [comment]
Looks like this is handled by the distro packaging.

Closing this PR.

**Pull request closed without merging**
