### PR TITLE
README: Add Debian dependency instructions

### PR DESCRIPTION
**Pull request by kirsle**
I managed to compile wayvnc for Mobian on Pinephone and identified the Debian names of dependencies needed.

These can be added to the README for posterity.

### CODE REVIEW

**Comment by any1** [comment]
Looks about right, which version of debian is that?

**Comment by kirsle** [comment]
It's on Debian Buster, the distro that [Mobian](https://mobian-project.org/) for the Pinephone is built from. Mobian uses upstream Buster packages except for a small handful of overrides for mobile-friendly app patches, while they await upstreaming their patches to Debian proper.

**Comment by any1** [comment]
Hmm, wayvnc requires libxkbcommon v1.0.0 or newer, but buster only has v0.8.2. I guess Mobian has a newer one?

**Comment by kirsle** [comment]
It looks like Debian testing has version 1.0.3-2: https://tracker.debian.org/pkg/libxkbcommon

```
[kirsle@pine ~]% apt search libxkbcommon-dev
Sorting... Done
Full Text Search... Done
libxkbcommon-dev/testing,now 1.0.3-2 arm64 [installed]
  library interface to the XKB compiler - development files
```

I guess I misspoke earlier, it's Debian bullseye, not buster; bullseye is currently in the testing freeze for an upcoming release.

**Comment by zerkman** [comment]
Hi, thanks for the patch but you left a typo : you wrote `libxbcommon-dev` instead of `libxkbcommon-dev`.

Otherwise it builds fine on Debian bullseye.

**Comment by Strbean1** [comment]
On Mobian I also needed to install `zlib1g-dev` in order to compile the neatvnc subproject.

**Comment by kirsle** [comment]
Updated the PR to fix the libxkbcommon-dev typo and add zlib1g-dev.

**Comment by lack** [comment]
The current README has debian instructions now.

Closing this PR. Please feel free to rebase and reopen if the README needs more updating!

**Pull request closed without merging**
